### ISSUE TITLE
Not working any more with Chrome Version 86.0.4240.111 (a 64 bit)

### ISSUE THREAD

**Issue by antimix** [limura/CaptionSpeaker#1]
Hello, 
it seems that with the new Chrome Version 86.0.4240.111 (official Build) (a 64 bit) it does not work any more.
The caption speech is randomly blocked in a second or two.
Even going on the option page, and clicking TEST, it has the same effect: the speech starts and it is abruptly interrupted in a second or two. I never reach 3 seconds of speech.

I tried other similar extensions, and also them stopped to speech. 
So probably Google changed something the code of Chrome and the extension code should be adapted to the new situation.

Regards

**Comment by limura** [comment]
Hello. Thank you for the report.

I have checked with the three environments listed below and they all seem to be working properly.

- 86.0.4240.111（Official Build） （64 ビット） / Windows 10 Pro Version 1909 build 18363.1139
- 86.0.4240.111（Official Build） （64 ビット） / Windows 10 Pro Version 1909 build 18363.1171
- 86.0.4240.111（Official Build） （x86_64）/ macOS Catalina Version 10.15.7

It may be that the problem is specific to your environment.

For these reasons, we won't take any action on this matter at this time as it depends on your environment.


This text was translated by DeepL.
The following is the original Japanese text:

こんにちは。報告ありがとうございます。

以下に上げる2つの環境で確認してみましたところ、それぞれ正常に動作しているように見受けられました。

- 86.0.4240.111（Official Build） （64 ビット） / Windows 10 Pro Version 1909 build 18363.1139
- 86.0.4240.111（Official Build） （64 ビット） / Windows 10 Pro Version 1909 build 18363.1171
- 86.0.4240.111（Official Build） （x86_64）/ macOS Catalina Version 10.15.7


もしかすると、そちらでお使いの環境特有の問題である可能性がありそうです。

以上の理由により、今の所この件に関しては利用環境による問題としてこちらからは何もしないことにします。

**Comment by limura** [comment]
Google Chrome has been updated and I checked again for this issue, but I couldn't see the problem.

Also, since it doesn't seem to provide any information that would allow me to reproduce the problem, I'll assume this is an environment-specific issue and close it.


This text was translated by DeepL.
The following is the original Japanese text:

Google Chrome が更新されたので再度この問題について確認しましたが、問題は確認できませんでした。

また、再現できるための情報も提供されないようですのでこの問題は環境特有の問題であるとし、closeします。
