### ISSUE TITLE
VLC and POTPLAYER

### ISSUE THREAD

**Issue by Nickyg001** [limura/CaptionSpeaker#2]
I discovered this extension for chrome and I fell in love with it, I was wondering if it was possible to have the same functionality of this extension for chrome also for software such as VLC player or POTPLAYER so as to have a reading of the subtitles in the preferred language also for videos we have in the PC and not just for videos on Youtube.

**Comment by limura** [comment]
I'm not familiar with the VLC and POTPLAYER extensions.
Can they use the JavaScript and window.speechSynthesis that CaptionSpeaker is using?

Also, even if they are available, it seems to me that the right thing to do would be to create and implement a separate project for VLC or POTPLAYER, rather than doing it in a project called CaptionSpeaker.

Therefore, I reject this proposal.


The original Japanese text is as follows:

VLC や POTPLAYER の extension について詳しくないのですが、
それらは CaptionSpeaker の使っている JavaScript や window.speechSynthesis が使えるのでしょうか？

また、もしそれらが使えたとしても、CaptionSpeaker というプロジェクトで行うよりは、VLC や POTPLAYER 向けに別のプロジェクトを作って実装するのが正道だと思われます。

従いまして、この提案は却下します。
